name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Docker Auth'
        uses: docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'us-central1-docker.pkg.dev'

      - name: 'Build and Push with Docker'
        run: |
          IMAGE="us-central1-docker.pkg.dev/sighthound-464019/car-crash-api:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - id: 'deploy'
        name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'car-crash-api'
          region: 'us-central1'
          image: 'us-central1-docker.pkg.dev/sighthound-464019/car-crash-api:${{ github.sha }}'

      - name: 'Show Cloud Run URL'
        run: echo "✅ Deployed to ${{ steps.deploy.outputs.url }}"
