name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: sighthound-464019
  LOCATION: europe-west1
  REPO: car-crash-api
  SERVICE: car-damage-api
  IMAGE: us-central1-docker.pkg.dev/sighthound-464019/car-crash-api/car-damage-api

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          token_format: 'access_token'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build . \
            --tag ${{ env.IMAGE }}:latest

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE }}:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}:latest
          region: ${{ env.LOCATION }}
          flags: '--allow-unauthenticated'
