name: 'Build and Deploy to Cloud Run'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Debug Auth Outputs'
        run: |
          echo "access_token=${{ steps.auth.outputs.access_token }}"
          echo "auth_token=${{ steps.auth.outputs.auth_token }}"
